Repository shinhan-flow/shinhan-flow-service, pull requests merged in 2024-08, with the labels that each got.

#6 chore: 프로젝트 생성 및 설정
  be/ShinhanFlow/.gitignore
  be/ShinhanFlow/build.gradle
  be/ShinhanFlow/gradle/wrapper/gradle-wrapper.jar
  be/ShinhanFlow/gradle/wrapper/gradle-wrapper.properties
  be/ShinhanFlow/gradlew
  be/ShinhanFlow/gradlew.bat
  be/ShinhanFlow/settings.gradle
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/ShinhanFlowApplication.java
  be/ShinhanFlow/src/main/resources/application.yml
  be/ShinhanFlow/src/test/java/com/ssafy/shinhanflow/ShinhanFlowApplicationTests.java
Labels: 🚀BE, ⚙️chore

#17 feat: Action, Trigger interface 작성
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/action/Action.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/trigger/Trigger.java
Labels: 🚀BE, ✨feat

#19 chore: root project gitignore 추가
  .gitignore
Labels: 🚀BE, ⚙️chore

#33 feat: jpa entity 설정
  .gitignore
  be/ShinhanFlow/.gitignore
  be/ShinhanFlow/build.gradle
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/ShinhanFlowApplication.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/entity/ActionEntity.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/entity/FlowEntity.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/entity/MemberEntity.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/entity/TriggerEntity.java
  be/ShinhanFlow/src/main/resources/application.yml
Labels: 🚀BE, ✨feat

#36 feat: 트리거 로직 구현
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/entity/ActionEntity.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/entity/FlowEntity.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/entity/MemberEntity.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/entity/TriggerEntity.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/trigger/TriggerFactory.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/trigger/account/BalanceTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/trigger/account/DepositTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/trigger/account/TransferTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/trigger/account/WithDrawTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/trigger/date/DayOfMonthTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/trigger/date/DayOfWeekTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/trigger/date/MultiDateTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/trigger/date/PeriodDateTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/trigger/date/SpecificDateTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/trigger/exchange/ExchangeRateTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/trigger/product/InterestRateTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/trigger/time/SpecificTimeTrigger.java
Labels: 🚀BE, ✨feat

#38 feat: jwt 토큰 생성
  be/ShinhanFlow/build.gradle
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/auth/controller/AuthController.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/auth/custom/CustomUserDetailService.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/auth/custom/CustomUserDetails.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/auth/jwt/JWTFilter.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/auth/jwt/JWTUtil.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/auth/jwt/LoginFilter.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/auth/service/RefreshTokenService.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/CorsMvcConfig.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/SecurityConfig.java
Labels: 🚀BE, ✨feat

#42 25 feat response error 객체 생성
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/error/ErrorCode.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/error/ErrorResponse.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/error/SuccessResponse.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/error/exception/BadRequestException.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/error/exception/BusinessBaseException.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/error/exception/GlobalExceptionHandler.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/error/exception/NoResourceFoundException.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/error/exception/NotFoundException.java
Labels: 🚀BE, ✨feat

#43 feat: 트리거 시간 설정 화면 구현
  fe/lib/common/component/table_calendar.dart
  fe/lib/flow/model/enum/widget/trigger_enum.dart
  fe/lib/flow/param/enum/flow_type.dart
  fe/lib/flow/param/trigger/trigger_date_time_param.dart
  fe/lib/flow/param/trigger/trigger_param.dart
  fe/lib/flow/provider/widget/flow_form_provider.dart
  fe/lib/flow/provider/widget/time_form_provider.dart
  fe/lib/flow/view/flow_init_screen.dart
  fe/lib/trigger/model/enum/time_category.dart
  fe/lib/trigger/view/time_trigger_screen.dart
Labels: 🗺️FE, ✨feat

#41 feat: 금융망 api 호출 service 구현
  be/ShinhanFlow/build.gradle
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/SecurityConfig.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/WebClientConfig.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/finance/FinanceController.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/finance/FinanceService.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/finance/dto/FinanceApiRequestDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/finance/dto/FinanceApiResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/finance/dto/MemberRequestDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/finance/dto/MemberResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/financeapi/FinanceApiFetcher.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/member/MemberController.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/member/MemberService.java
Labels: 🚀BE, ✨feat

#59 feat: 금융망 api 오류 client에게 전달
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/error/ErrorResponse.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/error/exception/FinanceApiException.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/error/exception/GlobalExceptionHandler.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/financeapi/FinanceApiFetcher.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/financeapi/dto/FinanceApiErrorBody.java
Labels: 🚀BE

#60 50 feat auth fcm api
  fe/.gitignore
  fe/android/app/build.gradle
  fe/android/app/src/main/AndroidManifest.xml
  fe/android/app/src/main/kotlin/com/shinhanflow/shflow/MainActivity.kt
  fe/android/settings.gradle
  fe/ios/Podfile
  fe/ios/Runner.xcodeproj/project.pbxproj
  fe/ios/Runner.xcworkspace/contents.xcworkspacedata
  fe/ios/Runner/AppDelegate.swift
  fe/ios/Runner/Info.plist
  fe/ios/Runner/Runner.entitlements
  fe/lib/auth/model/login_model.dart
  fe/lib/auth/param/login_param.dart
  fe/lib/auth/provider/auth_provider.dart
  fe/lib/auth/provider/login_provider.dart
  fe/lib/auth/provider/sign_up_provider.dart
  fe/lib/auth/provider/widget/widget/login_form_provider.dart
  fe/lib/auth/provider/widget/widget/sign_up_form_provider.dart
  fe/lib/auth/repository/auth_repository.dart
  fe/lib/auth/view/login_screen.dart
  fe/lib/common/model/default_model.dart
  fe/lib/common/provider/router_provider.dart
  fe/lib/dio/dio_interceptor.dart
  fe/lib/main.dart
  fe/lib/notification/param/notification_param.dart
  fe/lib/notification/provider/notification_provider.dart
  fe/lib/permission_screen.dart
  fe/lib/splash_screen.dart
Labels: 🗺️FE

#57 feat: 금융망 api 입출금 계좌
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/auth/jwt/JWTUtil.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/error/ErrorCode.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/finance/FinanceController.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/finance/FinanceService.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/finance/controller/DemandDepositController.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/finance/dto/FinanceApiRequestDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/finance/dto/account/DemandDepositBalanceRequestDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/finance/dto/account/DemandDepositBalanceResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/finance/dto/account/DemandDepositHolderRequestDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/finance/dto/account/DemandDepositHolderResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/finance/dto/account/DemandDepositRequestDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/finance/dto/account/DemandDepositResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/finance/dto/header/RequestHeaderDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/finance/dto/header/ResponseHeaderDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/finance/service/DemandDepositService.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/member/MemberService.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/util/FinanceApiFetcher.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/util/FinanceApiHeaderGenerator.java
Labels: 🚀BE, ✨feat

#64 feat: 액션 로직 구현
  be/ShinhanFlow/.gitignore
  be/ShinhanFlow/build.gradle
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/FirebaseConfig.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/entity/MemberEntity.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/flow/action/Action.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/flow/action/ActionFactory.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/flow/action/ExchangeAction.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/flow/action/TransferAction.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/flow/action/notification/BalanceNotificationAction.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/flow/action/notification/ExchangeRateNotificationAction.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/flow/action/notification/TextNotificationAction.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/flow/trigger/Trigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/flow/trigger/TriggerFactory.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/flow/trigger/account/BalanceTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/flow/trigger/account/DepositTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/flow/trigger/account/TransferTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/flow/trigger/account/WithDrawTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/flow/trigger/date/DayOfMonthTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/flow/trigger/date/DayOfWeekTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/flow/trigger/date/MultiDateTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/flow/trigger/date/PeriodDateTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/flow/trigger/date/SpecificDateTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/flow/trigger/exchange/ExchangeRateTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/flow/trigger/product/InterestRateTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/flow/trigger/time/SpecificTimeTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/util/FcmMessageRequestDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/util/FirebaseCloudMessageService.java
Labels: 🚀BE, ✨feat

#67 feat : 모든 예제 작성 및 추가
  ai/example/ans/ex10_blogging.py_ans1.txt
  ai/example/ans/ex10_blogging.py_ans2.txt
  ai/example/ex1.py
  ai/example/ex10_blogging.py
  ai/example/ex2.py
  ai/example/ex3.py
  ai/example/ex4.py
  ai/example/ex5.py
  ai/example/ex6_multi_persona.py
  ai/example/ex7_give_thinking_time.py
  ai/example/ex8_set_format.py
  ai/example/ex9_auto.py
Labels: 🤖AI, ✨feat

#74 feat: financeapifetcher의 fetch 함수 에러 핸들링 업데이트
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/error/exception/FinanceApiException.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/error/exception/GlobalExceptionHandler.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/util/FinanceApiFetcher.java
Labels: ✨feat

#82 feat: 수시입출금 계좌 조회 기능 추가
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/controller/finance/CurrentAccountController.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/current/CurrentAccountInfoListResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/current/CurrentAccountInfoRequestDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/current/CurrentAccountInfoResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/current/DepositAccountInfoResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/service/finance/CurrentAccountService.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/util/FinanceApiService.java
Labels: 🚀BE, ✨feat

#87 feat: swagger 추가
  be/ShinhanFlow/build.gradle
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/SecurityConfig.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/SwaggerConfig.java
Labels: 🚀BE, 📝docs

#90 feat: 금융망 api 예금 적금 대출 상품 조회 기능 추가
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/controller/finance/FinanceProductController.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/current/DepositAccountInfoResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/product/DepositAndSavingProductsRequestDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/product/DepositAndSavingProductsResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/product/LoanProductsRequestDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/product/LoanProductsResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/service/finance/FinanceProductService.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/util/FinanceApiService.java
Labels: 🚀BE, ✨feat

#93 refactor: 로그인 응답 수정
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/auth/dto/LoginSuccessResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/auth/jwt/LoginFilter.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/error/ErrorCode.java
Labels: 🚀BE, 🔧refactor

#95 feat: 금융망 api 수시입출금 상품 목록 확인
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/controller/finance/FinanceProductController.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/current/CurrentAccountProductRequestDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/current/CurrentAccountProductResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/service/finance/FinanceProductService.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/util/FinanceApiService.java
Labels: 🚀BE, ✨feat

#97 feat: made it to reuse emails already registered at finance api db
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/util/FinanceApiService.java
Labels: 🚀BE, ✨feat

#89 feat: 플로우 목록 가져오기
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/controller/flow/FlowController.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/flow/GetFlowListResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/service/flow/FlowService.java
Labels: 🚀BE, ✨feat

#98 88 feat 최근 입출금내역 가져오기 금융망 api 구현
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/controller/finance/CurrentAccountController.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/current/CurrentAccountTransactionHistoryRequestDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/current/CurrentAccountTransactionHistoryResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/service/finance/CurrentAccountService.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/util/FinanceApiService.java
Labels: 🚀BE, ✨feat

#101 feat: 환율 조회 api 구현
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/JacksonConfig.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/WebClientConfig.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/controller/finance/ExchangeRateController.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/exchange/ExchangeRateRequestDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/exchange/ExchangeRateResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/exchange/ExchangeRatesRequestDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/exchange/ExchangeRatesResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/service/finance/ExchangeRateService.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/util/CustomBigDecimalDeserializer.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/util/FinanceApiService.java
Labels: 🚀BE, ✨feat

#106 fix: remove custom deserializer
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/JacksonConfig.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/WebClientConfig.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/exchange/ExchangeRateResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/exchange/ExchangeRatesResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/util/CustomBigDecimalDeserializer.java
Labels: 🚀BE, 🐞bug

#115 feat: exchange rate trigger 구현
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/trigger/exchange/ExchangeRateTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/trigger/product/InterestRateTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/exchange/ExchangeRateResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/exchange/ExchangeRatesResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/service/finance/FinanceTriggerService.java
Labels: 🚀BE, ✨feat

#122 feat : 프롬프트 프로토타입(ver1) 완성
  ai/info.json
  ai/model_ver1.py
  ai/prompt/enumerate_actions.json
  ai/prompt/enumerate_triggers.json
  ai/prompt/explain_flow.json
  ai/prompt/set_data_format.json
  ai/prompt/set_output_format.json
  ai/tmp.py
Labels: 🤖AI, ✨feat

#121 feat: 환전 기능 구현
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/error/FinanceApiErrorBody.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/controller/finance/ExchangeController.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/exchange/ExchangeRequestDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/exchange/ExchangeResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/service/finance/ExchangeService.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/util/FinanceApiFetcher.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/util/FinanceApiService.java
Labels: 🚀BE, ✨feat

#112 feat: flow 활성화/비활성화
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/controller/flow/FlowController.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/entity/FlowEntity.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/service/flow/FlowService.java
Labels: 🚀BE, ✨feat

#127 feat: 로그인시 fcm 토큰 저장
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/auth/custom/CustomAuthenticationToken.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/auth/custom/CustomUserDetails.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/auth/jwt/LoginFilter.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/SecurityConfig.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/entity/MemberEntity.java
Labels: 🚀BE, ✨feat

#120 feat: 금융망 api의 계좌 관련 클래스 istriggered 구현
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/error/ErrorCode.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/controller/flow/FlowController.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/entity/MemberEntity.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/trigger/account/BalanceTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/trigger/account/DepositTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/trigger/account/WithDrawTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/current/CurrentAccountBalanceResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/current/CurrentAccountHolderResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/current/CurrentAccountTransactionHistoryResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/repository/MemberRepository.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/service/finance/FinanceTriggerService.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/service/flow/FlowService.java
Labels: 🚀BE, ✨feat

#134 133 feat 금융api 수시입출금 계좌 삭제 구현
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/controller/finance/CurrentAccountController.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/current/CurrentAccountDeleteRequestDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/current/CurrentAccountDeleteResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/service/finance/CurrentAccountService.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/util/FinanceApiService.java
Labels: 🚀BE, ✨feat

#141 fix: Trigger의 isTriggered메서드 userId 추가
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/trigger/Trigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/trigger/account/BalanceTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/trigger/account/DepositTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/trigger/account/TransferTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/trigger/account/WithDrawTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/trigger/date/DayOfMonthTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/trigger/date/DayOfWeekTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/trigger/date/MultiDateTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/trigger/date/PeriodDateTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/trigger/date/SpecificDateTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/trigger/exchange/ExchangeRateTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/trigger/product/InterestRateTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/trigger/time/SpecificTimeTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/service/finance/FinanceTriggerService.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/service/flow/FlowService.java
Labels: 🚀BE, ✨feat

#145 feat: implemented exchange rate notify action
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/action/ExchangeRateNotificationAction.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/service/flow/FinanceActionService.java
Labels: 🚀BE, ✨feat

#166 chore: update aigitignore
  ai/.gitignore
  ai/__pycache__/chat.cpython-38.pyc
  ai/__pycache__/utils.cpython-38.pyc
Labels: ⚙️chore

#167 feat: created basic lambda_function.py
  ai/lambda_function.py
Labels: 🤖AI, ⚙️chore

#165 feat: user 정보를 반환하는 api 구현
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/auth/controller/AuthController.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/auth/dto/UserDetailDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/auth/service/AuthService.java
Labels: 🚀BE, ✨feat

#168 feat: 사용자 신용점수 entity 생성
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/controller/member/MemberController.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/member/CreditScoreRequestDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/member/CreditScoreResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/service/member/MemberService.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/util/FinanceApiService.java
Labels: 🚀BE, ✨feat

#170 feat : model2 add
  ai/back_up/tmp2.py
  ai/chat.py
  ai/main.py
  ai/tmp2.py
Labels: 🤖AI, ✨feat

#177 174 feat 에러처리
  ai/chat.py
  ai/main.py
  ai/prompt/rule_generator.json
  ai/prompt/ver1/set_output_format.json
  ai/prompt/ver2/after_error_check.json
  ai/prompt/ver2/pre_error_check.json
  ai/prompt/ver3/check_action_value.json
  ai/prompt/ver3/check_list.json
  ai/prompt/ver3/check_trigger_value.json
  ai/prompt/ver3/disc_check_output.json
  ai/prompt/ver3/error_rule.json
  ai/tmp2.py
Labels: 🤖AI, ✨feat

#176 refactor: 환율 조회 api 신용정보 조회 api 리팩토링
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/controller/finance/ExchangeRateController.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/controller/member/MemberController.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/entity/CreditScoreEntity.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/entity/ExchangeRateEntity.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/domain/trigger/time/SpecificTimeTrigger.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/exchange/ExchangeRateDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/member/CreditScoreResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/repository/CreditScoreRepository.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/repository/ExchangeRateRepository.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/scheduler/DateScheduler.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/service/finance/ExchangeRateService.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/service/member/MemberService.java
Labels: 🚀BE, 🔧refactor

#185 175 feat spring 서버에서 lambda 함수 호출 기능 구현
  be/ShinhanFlow/build.gradle
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/config/AwsConfig.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/controller/ai/FlowGeneratorController.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/ai/FlowGeneratorLambdaFunctionRequestBodyDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/ai/FlowGeneratorLambdaFunctionResponseBodyDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/ai/FlowGeneratorRequestDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/ai/FlowGeneratorResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/service/ai/FlowGeneratorService.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/util/LambdaFunctionInvoker.java
Labels: 🚀BE, 🤖AI, 🌐infra, ⚙️chore

#187 feat: 예금 적금 대출 상품 등록 api 개발
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/controller/finance/ExchangeRateController.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/controller/finance/FinanceProductController.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/product/DepositAndSavingProductCreateRequestDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/product/DepositAndSavingProductCreateResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/product/LoanProductCreateRequestDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/dto/finance/product/LoanProductCreateResponseDto.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/service/finance/FinanceProductService.java
  be/ShinhanFlow/src/main/java/com/ssafy/shinhanflow/util/FinanceApiService.java
Labels: 🚀BE, ✨feat
